// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5t_f4fJd2LfZaU_oyxeYNX1geZ2KZ49k',
    appId: '1:343930647391:web:adf9a53c98d329991ebcea',
    messagingSenderId: '343930647391',
    projectId: 'career-guidance-85651',
    authDomain: 'career-guidance-85651.firebaseapp.com',
    databaseURL: 'https://career-guidance-85651-default-rtdb.firebaseio.com',
    storageBucket: 'career-guidance-85651.appspot.com',
    measurementId: 'G-LMJXC3649T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjI7DzC10DVbGsEUFw-kYVmaYDF5mPycA',
    appId: '1:343930647391:android:157117490c1698501ebcea',
    messagingSenderId: '343930647391',
    projectId: 'career-guidance-85651',
    databaseURL: 'https://career-guidance-85651-default-rtdb.firebaseio.com',
    storageBucket: 'career-guidance-85651.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe8eLDtxcy_ku82aZ-tdOrHnHHnUj-2NA',
    appId: '1:343930647391:ios:0dee112d844851531ebcea',
    messagingSenderId: '343930647391',
    projectId: 'career-guidance-85651',
    databaseURL: 'https://career-guidance-85651-default-rtdb.firebaseio.com',
    storageBucket: 'career-guidance-85651.appspot.com',
    iosBundleId: 'com.example.mobileAppMiniProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe8eLDtxcy_ku82aZ-tdOrHnHHnUj-2NA',
    appId: '1:343930647391:ios:0dee112d844851531ebcea',
    messagingSenderId: '343930647391',
    projectId: 'career-guidance-85651',
    databaseURL: 'https://career-guidance-85651-default-rtdb.firebaseio.com',
    storageBucket: 'career-guidance-85651.appspot.com',
    iosBundleId: 'com.example.mobileAppMiniProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5t_f4fJd2LfZaU_oyxeYNX1geZ2KZ49k',
    appId: '1:343930647391:web:aa59640bfc0b33481ebcea',
    messagingSenderId: '343930647391',
    projectId: 'career-guidance-85651',
    authDomain: 'career-guidance-85651.firebaseapp.com',
    databaseURL: 'https://career-guidance-85651-default-rtdb.firebaseio.com',
    storageBucket: 'career-guidance-85651.appspot.com',
    measurementId: 'G-625BEHN7W1',
  );
}
